title: Mohamedelhassan M.Mahjob
logo: assets/images/profile_pic.jpg
show_downloads: True
plugins:
- jekyll-remote-theme 
theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
